version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.18.3-browsers

    working_directory: ~/repo/FrontEnd

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

  # Back End
  BackEndTest:
    working_directory: ~/repo/BackEnd/assignment1
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: ./mvnw test

  BackEndBuild:
    working_directory: ~/repo/BackEnd/assignment1
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: ./mvnw -Dmaven.test.skip=true package

workflows:
  version: 2

  build-then-test:
    jobs:
      - BackEndBuild
      - BackEndTest:
          requires:
            - build