version: 2
     
jobs:
  # Back End
  BackBuild:
    working_directory: ~/repo/BackEnd/assignment1
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout:
          path: ~/repo
      - run: ./mvnw -Dmaven.test.skip=true package
  BackTest:
    working_directory: ~/repo/BackEnd/assignment1
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout:
          path: ~/repo
      - run: ./mvnw test
  #Front end
  FrontTest:
    docker:
      - image: circleci/node:12.18.3-browsers
    working_directory: ~/repo/FrontEnd
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test

workflows:
  version: 2

  build-then-test:
    jobs:
      - BackBuild:
          filters:
            branches:
              only: master
      - BackTest:
          requires:
            - BackBuild
          filters:
            branches:
              only: master
      - FrontTest:
          requires:
            - BackBuild
          filters:
            branches:
              only: master
